name: TownyResidency
version: '1.0.0'
main: de.nikdev.townyResidency.TownyResidency
api-version: '1.21'
authors: [ NikDev ]
description: A Plugin that goes into the roleplay aspects of residency within Towny
depend: [Towny]
commands:
  residency:
    description: Gives out the town and nation of a player
    usage: /<command>
